<?php
require_once 'functions.php'; require_login();
$user=current_user();$uid=$user['id'];
$stmt=$pdo->prepare('SELECT COUNT(*) FROM tasks WHERE user_id=?');$stmt->execute([$uid]);$total=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare("SELECT COUNT(*) FROM tasks WHERE user_id=? AND status='completed'");$stmt->execute([$uid]);$done=(int)$stmt->fetchColumn();
$percent=$total?round(($done/$total)*100):0;
$stmt=$pdo->prepare('SELECT subject, COUNT(*) total, SUM(status="completed") done FROM tasks WHERE user_id=? GROUP BY subject ORDER BY subject');$stmt->execute([$uid]);$subjects=$stmt->fetchAll();
$stmt=$pdo->prepare('SELECT priority, COUNT(*) total, SUM(status="completed") done FROM tasks WHERE user_id=? GROUP BY priority');$stmt->execute([$uid]);$priorities=$stmt->fetchAll();
app_header('StudyFlow – Progress');app_shell_start('progress');
?>
<section class="page active" id="progressPage"><div class="page-header"><div><h2 class="page-title">Progress</h2><p class="page-subtitle">Track your learning journey</p></div></div>
<div class="progress-grid"><div class="card progress-hero"><div class="hero-circle-wrap"><svg class="hero-circle" viewBox="0 0 120 120"><circle cx="60" cy="60" r="50" class="circle-bg"></circle><circle cx="60" cy="60" r="50" class="circle-fill" style="stroke-dashoffset:<?= 314 - (314*$percent/100) ?>"></circle></svg><div class="hero-pct"><?= $percent ?>%</div></div><div class="hero-info"><h3 class="hero-title">Overall Completion</h3><p class="hero-sub">Keep going, you're doing great!</p><div class="hero-stats"><div class="hero-stat"><span class="hero-stat-val"><?= $done ?></span><span class="hero-stat-lbl">Done</span></div><div class="hero-stat"><span class="hero-stat-val"><?= $total ?></span><span class="hero-stat-lbl">Total</span></div><div class="hero-stat"><span class="hero-stat-val">7</span><span class="hero-stat-lbl">Streak</span></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">By Subject</h3></div><div class="subject-progress-list"><?php if(!$subjects): ?><div class="empty-state-sm">No subject data yet.</div><?php endif; ?><?php foreach($subjects as $s): $p=$s['total']?round(($s['done']/$s['total'])*100):0; ?><div class="subject-progress-item"><div class="subject-progress-top"><span><?= e($s['subject']) ?></span><span><?= $p ?>%</span></div><div class="progress-bar"><div class="progress-fill" style="width:<?= $p ?>%"></div></div></div><?php endforeach; ?></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">By Priority</h3></div><div class="priority-progress"><?php foreach($priorities as $p): ?><div class="priority-item"><span class="task-mini-badge badge-<?= e($p['priority']) ?>"><?= e($p['priority']) ?></span><span><?= (int)$p['done'] ?> / <?= (int)$p['total'] ?> completed</span></div><?php endforeach; ?></div></div>
<div class="card achievements-card"><div class="card-header"><h3 class="card-title">🏆 Achievements</h3></div><div class="achievements-grid"><div class="achievement unlocked">✅ First Task</div><div class="achievement <?= $done>=5?'unlocked':'' ?>">🔥 5 Tasks Done</div><div class="achievement <?= $percent>=80?'unlocked':'' ?>">⭐ 80% Complete</div></div></div></div></section><?php app_shell_end(); ?>
